## Logic REgression Using python and sklearn

In [43]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [44]:
from sklearn.datasets import make_classification

In [65]:
## create the data set
X,y = make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=44)

In [66]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0    0.667145 -0.020339  1.563118 -0.154670  0.397933 -0.724184 -1.812018   
1   -0.761265 -0.840965  2.790805  2.220647 -0.901718 -1.044482 -0.975207   
2   -1.660288  0.700077 -1.199443 -0.144914 -0.785627 -0.806654  1.151837   
3   -0.895767  1.920737 -0.781555 -0.601453  1.002203 -1.217053  0.291596   
4   -0.969944 -0.884422  1.440441 -0.128013 -1.134058  0.081523 -1.656666   
..        ...       ...       ...       ...       ...       ...       ...   
995 -0.467130  0.622259 -0.050239 -0.831479  0.370650  2.243060 -0.698878   
996 -0.590497 -0.071757 -1.288197 -2.149111 -0.866143  0.590101 -0.567334   
997 -0.547842 -1.092210  0.168831  0.437432 -0.014449 -0.048558  0.215351   
998  1.021133  0.113338  1.012407  3.621332  0.442857  1.456792  2.194926   
999 -0.094003  0.745391  0.685315  0.036609 -0.986560 -0.541748 -0.699924   

            7         8         9  
0    1.595068  1.637143  0.630641  
1    0.244041 -0.433900  0.823214  
2   -0.949064 -1.402173 -1.691767  
3   -0.089649  0.512538  0.995144  
4    1.454743 -1.589212  1.323239  
..        ...       ...       ...  
995  0.821034  0.534935  0.454071  
996  1.059623 -1.280919 -1.701569  
997 -0.301320  0.542015  0.030091  
998 -2.847912 -0.852258  1.477062  
999  0.590427  0.286214 -0.957027  

[1000 rows x 10 columns]

In [67]:
## train test split 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=44)

In [68]:
X_train.shape,X_train

((700, 10),
 array([[-1.2316486 , -0.19508738, -0.88259297, ..., -0.89317748,
          0.95243134, -0.32335724],
        [ 0.19947303,  0.844409  , -1.2716636 , ..., -1.66249218,
          0.87512365, -0.89459454],
        [ 0.20174426,  0.50369541, -0.8463992 , ..., -0.31184889,
         -2.15614575,  0.99544292],
        ...,
        [-1.02571132, -0.04427641,  0.49914673, ...,  0.69104703,
          0.04061293,  3.34906069],
        [ 0.23071363,  0.1091681 ,  0.5262479 , ...,  0.5553741 ,
          0.17000333,  0.23508552],
        [ 0.54200023, -0.49123267, -0.94488753, ..., -0.33796082,
          0.36460019, -0.18088039]], shape=(700, 10)))

In [69]:
## model training 
from sklearn.linear_model import LogisticRegression

In [70]:
logictic = LogisticRegression()

In [71]:
logictic.fit(X_train,y_train)

LogisticRegression()

In [72]:
y_pred=logictic.predict(X_test)
print(y_pred)

[1 0 0 1 1 1 0 0 0 1 1 1 0 0 1 1 1 1 0 1 0 0 0 0 0 0 1 1 0 1 0 0 1 1 0 1 0
 0 1 0 1 1 1 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0 1 1 0 1 0 0 1 1 0 1 1 1 1 0 1 1
 0 0 1 1 1 0 1 0 1 0 0 0 0 1 1 1 0 0 0 0 0 1 0 1 1 0 1 1 0 1 0 1 0 0 1 0 0
 0 0 1 0 0 1 0 0 1 0 0 1 0 1 1 0 1 1 1 1 0 1 1 0 1 1 0 0 0 1 0 1 1 1 0 1 0
 1 0 0 0 0 1 0 0 1 1 1 0 1 1 1 0 0 1 1 1 0 1 0 1 0 1 1 0 1 1 0 1 0 0 0 0 0
 0 0 0 1 1 0 0 1 0 0 1 0 1 1 1 1 1 0 1 1 1 0 1 0 1 0 1 0 0 1 0 1 0 1 1 1 1
 1 0 0 0 0 1 1 1 1 0 1 1 0 0 1 0 0 1 1 0 0 1 1 0 1 0 0 0 0 1 1 1 1 1 1 0 1
 1 0 1 1 0 0 1 0 1 1 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 1 1 1 0 0 1 1 0 0 0 0
 1 0 0 1]


In [73]:
logictic.predict_proba(X_test)

array([[5.51130795e-06, 9.99994489e-01],
       [7.05692595e-01, 2.94307405e-01],
       [8.01990980e-01, 1.98009020e-01],
       [1.33451078e-04, 9.99866549e-01],
       [1.05636490e-01, 8.94363510e-01],
       [5.80858003e-02, 9.41914200e-01],
       [9.94537012e-01, 5.46298793e-03],
       [9.40168685e-01, 5.98313146e-02],
       [6.70962782e-01, 3.29037218e-01],
       [4.15098552e-01, 5.84901448e-01],
       [2.77234388e-03, 9.97227656e-01],
       [4.39345274e-04, 9.99560655e-01],
       [9.99545800e-01, 4.54199931e-04],
       [8.62465235e-01, 1.37534765e-01],
       [1.10453007e-02, 9.88954699e-01],
       [1.94184356e-03, 9.98058156e-01],
       [7.67750977e-04, 9.99232249e-01],
       [1.50741178e-02, 9.84925882e-01],
       [8.14548072e-01, 1.85451928e-01],
       [3.70270885e-03, 9.96297291e-01],
       [9.85393828e-01, 1.46061716e-02],
       [7.97861085e-01, 2.02138915e-01],
       [9.35959529e-01, 6.40404706e-02],
       [9.99066764e-01, 9.33235984e-04],
       [9.997171

In [74]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report


In [75]:
score=accuracy_score(y_test,y_pred)
print(score)
cm = confusion_matrix(y_test,y_pred)
print(cm)
cr = classification_report(y_test,y_pred)
print(cr)

0.8933333333333333
[[131  12]
 [ 20 137]]
              precision    recall  f1-score   support

           0       0.87      0.92      0.89       143
           1       0.92      0.87      0.90       157

    accuracy                           0.89       300
   macro avg       0.89      0.89      0.89       300
weighted avg       0.89      0.89      0.89       300



## Hyperparameter Tuning And Cross Validation

In [76]:
model = LogisticRegression()
penalty = ['l1','l2','elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver = ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']

In [77]:
params = dict(penalty=penalty,C=c_values,solver=solver)

In [78]:
## Grid Search CV
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold()


In [79]:
grid = GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)

In [80]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [81]:
print(grid)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')


In [82]:
grid.fit(X_train,y_train)

d:\python programing\UD\MLBasics\LogisticRegression\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
250 fits failed out of a total of 450.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "d:\python programing\UD\MLBasics\LogisticRegression\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\python programing\UD\MLBasics\LogisticRegression\.venv\Lib\site-packages\sklearn\base.py", line 1363, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python 

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [83]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

In [84]:
grid.best_score_

np.float64(0.9228571428571428)

In [85]:
y_pred=grid.predict(X_test)

In [86]:
## performance metrics
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.8966666666666666
              precision    recall  f1-score   support

           0       0.87      0.92      0.89       143
           1       0.93      0.87      0.90       157

    accuracy                           0.90       300
   macro avg       0.90      0.90      0.90       300
weighted avg       0.90      0.90      0.90       300

[[132  11]
 [ 20 137]]


## Randomized SearchCV