#### This is a project of Kindle Reviews Sentimental Analysis

#### Best Practicing
##### 1. Preprocessing and Cleaning
##### 2. Train Test Split
##### 3. BOW,TF-IDF,Word2Vec
##### 4. Train ML Algorithms

In [111]:
## loading of data
import pandas as pd
df = pd.read_csv('Kindle Reviews/all_kindle_review.csv')
df.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       3   
1             1        5957  B002HJV4DE   [1, 1]       5   
2             2        9146  B002ZG96I4   [0, 0]       3   
3             3        7038  B002QHWOEU   [1, 3]       3   
4             4        1776  B001A06VJ8   [0, 1]       4   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [112]:
df = df[['reviewText','rating']]

In [113]:
df.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [114]:
df.shape

(12000, 2)

In [115]:
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [116]:
df['rating'].unique()

array([3, 5, 4, 2, 1], dtype=int64)

In [117]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [118]:
## Preprocessing and Cleaning
## positive review is 1 and negative review is 0
df['rating'] = df['rating'].apply(lambda x:0 if x < 3 else 1)

In [119]:
df['rating'].unique()

array([1, 0], dtype=int64)

In [120]:
df.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       1
1  Great short read.  I didn't want to put it dow...       1
2  I'll start by saying this is the first of four...       1
3  Aggie is Angela Lansbury who carries pocketboo...       1
4  I did not expect this type of book to be in li...       1

In [121]:
df['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [122]:
## lowering of all the cases
df['reviewText'] = df['reviewText'].str.lower()

In [123]:
df['reviewText']

0        jace rankin may be short, but he's nothing to ...
1        great short read.  i didn't want to put it dow...
2        i'll start by saying this is the first of four...
3        aggie is angela lansbury who carries pocketboo...
4        i did not expect this type of book to be in li...
                               ...                        
11995    valentine cupid is a vampire- jena and ian ano...
11996    i have read all seven books in this series. ap...
11997    this book really just wasn't my cuppa.  the si...
11998    tried to use it to charge my kindle, it didn't...
11999    taking instruction is a look into the often hi...
Name: reviewText, Length: 12000, dtype: object

In [124]:
df.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [125]:
print(df['reviewText'].head())

0    jace rankin may be short, but he's nothing to ...
1    great short read.  i didn't want to put it dow...
2    i'll start by saying this is the first of four...
3    aggie is angela lansbury who carries pocketboo...
4    i did not expect this type of book to be in li...
Name: reviewText, dtype: object


In [126]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from bs4 import BeautifulSoup

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [127]:
## Removing all the special characters and stopwords
df['reviewText'] = df['reviewText'].apply(lambda x: re.sub('[^a-zA-Z0-9- ]+','',x))
## Remove the stopwords
df['reviewText'] = df['reviewText'].apply(lambda x: " ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Removing the urls
df['reviewText'] = df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?','',str(x)))
## Remove Html Tags
df['reviewText'] = df['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
## Remove aditional spaces
df['reviewText'] = df['reviewText'].apply(lambda x: " ".join(x.split()))

In [145]:
df['reviewText'].head()

0    jace rankin may short he nothing mess man haul...
1    great short read didnt want put read one sitti...
2    ill start saying first four book wasnt expecti...
3    aggie angela lansbury carry pocketbook instead...
4    expect type book library pleased find price right
Name: reviewText, dtype: object

In [146]:
df.head()

reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [147]:
## applying lemmatization
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [148]:
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [149]:
df['reviewText'] = df['reviewText'].apply(lambda x: lemmatize_words(x))

In [150]:
df.head()

reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [151]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df['reviewText'],df['rating'],test_size=0.20)

In [152]:
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer()

In [153]:
X_train_bow = bow.fit_transform(X_train).toarray()
X_test_bow = bow.transform(X_test).toarray()

In [154]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train).toarray()
X_test_tfidf = tfidf.transform(X_test).toarray()

In [155]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [156]:
X_train_tfidf

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [157]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow = GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf = GaussianNB().fit(X_train_tfidf,y_train)

In [158]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [159]:
y_pred_bow = nb_model_bow.predict(X_test_bow)

In [160]:
y_pred_tfidf = nb_model_tfidf.predict(X_test_tfidf)

In [161]:
print(f"Bow Accuracy Score = {accuracy_score(y_test,y_pred_bow)}")
print(f"TFIDF Accuracy Score = {accuracy_score(y_test,y_pred_tfidf)}")

Bow Accuracy Score = 0.5741666666666667
TFIDF Accuracy Score = 0.5729166666666666


In [162]:
confusion_matrix(y_test,y_pred_bow)

array([[520, 304],
       [718, 858]], dtype=int64)

In [163]:
confusion_matrix(y_test,y_pred_tfidf)

array([[502, 322],
       [703, 873]], dtype=int64)

In [164]:
## Trying this with word to vec
import gensim

In [165]:
from gensim.models import word2vec,keyedvectors

In [166]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

In [168]:
## here i can again read the csv file 



In [169]:
print(df['reviewText'].head())

0    jace rankin may short he nothing mess man haul...
1    great short read didnt want put read one sitti...
2    ill start saying first four book wasnt expecti...
3    aggie angela lansbury carry pocketbook instead...
4    expect type book library pleased find price right
Name: reviewText, dtype: object


In [170]:
df['reviewText'].head()

0    jace rankin may short he nothing mess man haul...
1    great short read didnt want put read one sitti...
2    ill start saying first four book wasnt expecti...
3    aggie angela lansbury carry pocketbook instead...
4    expect type book library pleased find price right
Name: reviewText, dtype: object

In [171]:
df.head()

reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [172]:
## Tekenizing all the text 
df['token'] = df['reviewText'].apply(lambda x: x.split())
print(df['token'].head())

0    [jace, rankin, may, short, he, nothing, mess, ...
1    [great, short, read, didnt, want, put, read, o...
2    [ill, start, saying, first, four, book, wasnt,...
3    [aggie, angela, lansbury, carry, pocketbook, i...
4    [expect, type, book, library, pleased, find, p...
Name: token, dtype: object


In [175]:
import numpy as np
def avg_word2vec(token,model,vector_size=300):
    """
    Given a list of tokens and word2vec model return the average word vector
    """
    valid_vectors = [model[word] for word in token if word in model.key_to_index]
    if valid_vectors:
        return np.mean(valid_vectors,axis=0)
    else:
        return np.zeros(vector_size,dtype=np.float32)
    

In [177]:
example_token = df['token'].iloc[0]
print(avg_word2vec(example_token,wv).shape)

(300,)


In [178]:
## creating a new column in df for word2vec
df['word2vec'] = df['token'].apply(lambda tokens : avg_word2vec(tokens,wv,vector_size=300))


In [179]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [181]:
## Converting the word2vec column in to 2d array
X_word2vec = np.vstack(df['word2vec'].values)
y = df['rating'].values
print(X_word2vec.shape)

(12000, 300)


In [182]:
X_train,X_test,y_train,y_test = train_test_split(X_word2vec,y,test_size=0.20,random_state=42)

clf = GaussianNB()
clf.fit(X_train,y_train)


GaussianNB()

In [183]:
y_pred = clf.predict(X_test)

In [184]:
y_pred

array([1, 0, 0, ..., 1, 0, 1], dtype=int64)

In [185]:
accuracy_score(y_pred,y_test)

0.7445833333333334

In [187]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.59      0.79      0.67       803
           1       0.87      0.72      0.79      1597

    accuracy                           0.74      2400
   macro avg       0.73      0.76      0.73      2400
weighted avg       0.78      0.74      0.75      2400



In [188]:
from sklearn.ensemble import  RandomForestClassifier
classifier = RandomForestClassifier()

In [189]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [190]:
accuracy_score(y_pred,y_test)

0.7445833333333334