## Word2Vec

In [1]:
import gensim
from gensim.models import Word2Vec, KeyedVectors


In [3]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')
vec_king = wv['king']

In [4]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [8]:
import pandas as pd
messages = pd.read_csv('SpamClassifier-master/spam.csv', encoding='latin1',names=['label','message'],header=0,usecols=[0,1],sep=',')

In [9]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [14]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [19]:
corpus = []
for i in range(len(messages)):
    review = re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review = review.lower()
    review  =  review.split()
    review = [lemmatizer.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [20]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [22]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [27]:
words = []
for sent in corpus:
    sent_token = sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [28]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [89]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [29]:
import gensim

In [33]:
## Lets train word2vec from scrach
model = gensim.models.Word2Vec(words)

In [34]:
## to get all the vocabulary
model.wv.index_to_key

['you',
 'to',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'be',
 'if',
 'will',
 'ur',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'how',
 'go',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'out',
 'all',
 'know',
 'll',
 'come',
 'like',
 'time',
 'good',
 'then',
 'am',
 'got',
 'wa',
 'there',
 'he',
 'text',
 'only',
 'love',
 'want',
 'send',
 'txt',
 'need',
 'one',
 'today',
 'by',
 'going',
 'don',
 'home',
 'stop',
 'about',
 'she',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'our',
 'think',
 'dont',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'later',
 'they',
 'her',
 'any',
 'pls',
 'ha',
 'please',
 'co',
 'did',
 'msg',
 'been',
 'min',
 'some',
 'an',
 'make',
 'dear',
 'here',
 'night',
 'who',
 'message',
 'say',
 'well',
 're',
 'where',
 'thing',
 'much',
 'clai

In [35]:
model.corpus_count

5569

In [36]:
model.epochs

5

In [39]:
model.wv.similar_by_word('good')

[('day', 0.9990785717964172),
 ('my', 0.9989877343177795),
 ('where', 0.9989356398582458),
 ('well', 0.9988442063331604),
 ('hope', 0.9988393783569336),
 ('about', 0.9988351464271545),
 ('wa', 0.9988030195236206),
 ('and', 0.9987937808036804),
 ('love', 0.9987164735794067),
 ('morning', 0.9987104535102844)]

In [40]:
model.wv['good']

array([-0.28830132,  0.27817106,  0.2928009 ,  0.19615754,  0.15661573,
       -0.68754035,  0.28452283,  0.79556334, -0.27460352, -0.26768413,
       -0.2736979 , -0.66111946, -0.1265683 ,  0.1624022 ,  0.21710078,
       -0.27672338,  0.08053037, -0.4749731 , -0.01042678, -0.74109006,
        0.24865049,  0.305395  ,  0.21769539, -0.27194852, -0.01603585,
        0.08534753, -0.30825093, -0.36096704, -0.39462683, -0.02559899,
        0.3887237 ,  0.05084084,  0.22759217, -0.25522715, -0.1895718 ,
        0.5063019 ,  0.07599452, -0.34705725, -0.0997805 , -0.7279761 ,
        0.12484762, -0.21487212, -0.26488632,  0.05961353,  0.33068886,
       -0.16696791, -0.19664498, -0.0897699 ,  0.14269862,  0.28983137,
        0.18605553, -0.22065687, -0.16026552,  0.03428084, -0.15585753,
        0.16894443,  0.22753379,  0.19253685, -0.49949223,  0.21406262,
       -0.05066378, -0.00967155,  0.10750014, -0.1451337 , -0.51556087,
        0.3265276 ,  0.14372586,  0.25899914, -0.51282656,  0.43

In [42]:
model.wv['good'].shape

(100,)

In [43]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [90]:
def avg_word2vec(doc):
    ## remove out of vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)
    wordVector = [model.wv[word] for word in doc if word in model.wv.index_to_key]
    if not wordVector:
        return np.zeros(model.vector_size,dtype=np.float32)
    return np.mean(wordVector,axis=0)

In [91]:
import numpy as np
from tqdm import  tqdm

In [92]:
# apply for the entire sentences
X = []
for i in tqdm(range(len(words))):
    print("Hello",i)
    X.append(avg_word2vec(words[i]))

 24%|██▍       | 1362/5569 [00:00<00:00, 13568.90it/s]

Hello 0
Hello 1
Hello 2
Hello 3
Hello 4
Hello 5
Hello 6
Hello 7
Hello 8
Hello 9
Hello 10
Hello 11
Hello 12
Hello 13
Hello 14
Hello 15
Hello 16
Hello 17
Hello 18
Hello 19
Hello 20
Hello 21
Hello 22
Hello 23
Hello 24
Hello 25
Hello 26
Hello 27
Hello 28
Hello 29
Hello 30
Hello 31
Hello 32
Hello 33
Hello 34
Hello 35
Hello 36
Hello 37
Hello 38
Hello 39
Hello 40
Hello 41
Hello 42
Hello 43
Hello 44
Hello 45
Hello 46
Hello 47
Hello 48
Hello 49
Hello 50
Hello 51
Hello 52
Hello 53
Hello 54
Hello 55
Hello 56
Hello 57
Hello 58
Hello 59
Hello 60
Hello 61
Hello 62
Hello 63
Hello 64
Hello 65
Hello 66
Hello 67
Hello 68
Hello 69
Hello 70
Hello 71
Hello 72
Hello 73
Hello 74
Hello 75
Hello 76
Hello 77
Hello 78
Hello 79
Hello 80
Hello 81
Hello 82
Hello 83
Hello 84
Hello 85
Hello 86
Hello 87
Hello 88
Hello 89
Hello 90
Hello 91
Hello 92
Hello 93
Hello 94
Hello 95
Hello 96
Hello 97
Hello 98
Hello 99
Hello 100
Hello 101
Hello 102
Hello 103
Hello 104
Hello 105
Hello 106
Hello 107
Hello 108
Hello 109
Hello 110


 98%|█████████▊| 5466/5569 [00:00<00:00, 13513.05it/s]

Hello 2706
Hello 2707
Hello 2708
Hello 2709
Hello 2710
Hello 2711
Hello 2712
Hello 2713
Hello 2714
Hello 2715
Hello 2716
Hello 2717
Hello 2718
Hello 2719
Hello 2720
Hello 2721
Hello 2722
Hello 2723
Hello 2724
Hello 2725
Hello 2726
Hello 2727
Hello 2728
Hello 2729
Hello 2730
Hello 2731
Hello 2732
Hello 2733
Hello 2734
Hello 2735
Hello 2736
Hello 2737
Hello 2738
Hello 2739
Hello 2740
Hello 2741
Hello 2742
Hello 2743
Hello 2744
Hello 2745
Hello 2746
Hello 2747
Hello 2748
Hello 2749
Hello 2750
Hello 2751
Hello 2752
Hello 2753
Hello 2754
Hello 2755
Hello 2756
Hello 2757
Hello 2758
Hello 2759
Hello 2760
Hello 2761
Hello 2762
Hello 2763
Hello 2764
Hello 2765
Hello 2766
Hello 2767
Hello 2768
Hello 2769
Hello 2770
Hello 2771
Hello 2772
Hello 2773
Hello 2774
Hello 2775
Hello 2776
Hello 2777
Hello 2778
Hello 2779
Hello 2780
Hello 2781
Hello 2782
Hello 2783
Hello 2784
Hello 2785
Hello 2786
Hello 2787
Hello 2788
Hello 2789
Hello 2790
Hello 2791
Hello 2792
Hello 2793
Hello 2794
Hello 2795
Hello 2796

100%|██████████| 5569/5569 [00:00<00:00, 13447.57it/s]

Hello 5466
Hello 5467
Hello 5468
Hello 5469
Hello 5470
Hello 5471
Hello 5472
Hello 5473
Hello 5474
Hello 5475
Hello 5476
Hello 5477
Hello 5478
Hello 5479
Hello 5480
Hello 5481
Hello 5482
Hello 5483
Hello 5484
Hello 5485
Hello 5486
Hello 5487
Hello 5488
Hello 5489
Hello 5490
Hello 5491
Hello 5492
Hello 5493
Hello 5494
Hello 5495
Hello 5496
Hello 5497
Hello 5498
Hello 5499
Hello 5500
Hello 5501
Hello 5502
Hello 5503
Hello 5504
Hello 5505
Hello 5506
Hello 5507
Hello 5508
Hello 5509
Hello 5510
Hello 5511
Hello 5512
Hello 5513
Hello 5514
Hello 5515
Hello 5516
Hello 5517
Hello 5518
Hello 5519
Hello 5520
Hello 5521
Hello 5522
Hello 5523
Hello 5524
Hello 5525
Hello 5526
Hello 5527
Hello 5528
Hello 5529
Hello 5530
Hello 5531
Hello 5532
Hello 5533
Hello 5534
Hello 5535
Hello 5536
Hello 5537
Hello 5538
Hello 5539
Hello 5540
Hello 5541
Hello 5542
Hello 5543
Hello 5544
Hello 5545
Hello 5546
Hello 5547
Hello 5548
Hello 5549
Hello 5550
Hello 5551
Hello 5552
Hello 5553
Hello 5554
Hello 5555
Hello 5556

In [93]:
X

[array([-2.00217336e-01,  2.04333946e-01,  1.95312336e-01,  1.54776141e-01,
         9.68391448e-02, -4.76217836e-01,  1.70908689e-01,  5.50495446e-01,
        -2.16405049e-01, -1.66400105e-01, -2.07822427e-01, -4.38336939e-01,
        -7.94744343e-02,  1.18863970e-01,  1.42819196e-01, -1.97199926e-01,
         4.11101729e-02, -3.42618018e-01, -4.29014303e-03, -4.99175400e-01,
         1.70909658e-01,  1.83662444e-01,  1.61550909e-01, -1.62019581e-01,
        -3.91043909e-03,  7.92504698e-02, -2.09814847e-01, -2.35055864e-01,
        -2.70686686e-01,  2.36653344e-04,  2.54725486e-01,  2.59388201e-02,
         1.36752218e-01, -1.83869153e-01, -1.11884348e-01,  3.57812077e-01,
         5.20676188e-02, -2.38573328e-01, -7.97120035e-02, -5.11942923e-01,
         6.66196272e-02, -1.66513890e-01, -2.08557874e-01,  3.91696021e-02,
         2.03623772e-01, -1.24350347e-01, -1.19781472e-01, -6.80720434e-02,
         1.06992431e-01,  1.91407546e-01,  1.34545982e-01, -1.83889255e-01,
        -1.1

In [94]:
len(X)

5569

In [95]:
# independent features
X_new = np.array(X)

In [101]:
messages.shape

(5572, 2)

In [96]:
X_new.shape

(5569, 100)

In [97]:
X_new[0].shape

(100,)

In [98]:
## Dependent Features
y = pd.get_dummies(messages['label'])
y = y.iloc[:,0].values

In [99]:
y

array([ True,  True, False, ...,  True,  True,  True])

In [100]:
y.shape

(5572,)

In [107]:
X[0].reshape(1,-1).shape

(1, 100)

In [112]:
## this is the final independent features
rows_list = []
for i in range(0,len(X)):
    row_df = pd.DataFrame(X[i].reshape(1,-1))
    rows_list.append(row_df)
if rows_list:
    df = pd.concat(rows_list,ignore_index=True)
else:
    df = pd.DataFrame()

In [113]:
df.shape

(5569, 100)

In [114]:
df.head

<bound method NDFrame.head of             0         1         2         3         4         5         6   \
0    -0.200217  0.204334  0.195312  0.154776  0.096839 -0.476218  0.170909   
1    -0.185282  0.176578  0.165189  0.129798  0.089715 -0.407780  0.141470   
2    -0.222501  0.207733  0.236150  0.216585  0.110113 -0.529273  0.140634   
3    -0.284592  0.280867  0.255577  0.200939  0.129222 -0.643226  0.240909   
4    -0.234159  0.230360  0.223276  0.161844  0.120448 -0.541124  0.199905   
...        ...       ...       ...       ...       ...       ...       ...   
5564 -0.245666  0.240304  0.264596  0.223209  0.116782 -0.592849  0.190474   
5565 -0.258444  0.239312  0.235779  0.191203  0.135084 -0.577172  0.195241   
5566 -0.275878  0.276075  0.261467  0.196405  0.127806 -0.640748  0.238631   
5567 -0.249281  0.248529  0.243976  0.191353  0.123964 -0.585786  0.204758   
5568 -0.274645  0.264111  0.258964  0.197326  0.143662 -0.627309  0.223490   

            7         8         9

In [115]:
## independent feature
X = df

In [118]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.20)

ValueError: Found input variables with inconsistent numbers of samples: [5569, 5572]